[package]
name = "plugin_impl"
version = "0.1.0"
authors = ["OnlyOneFace <13522570308@139.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crochee_plugin = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]